// Auto-generated from core/templates/environment.ts + app-config.json
export const environment = {
    FACEBOOK_APP_VERSION: "v19.0",
    GOOGLE_CONTACT_SCOPE: "https://www.googleapis.com/auth/contacts.readonly",
    API: "{{apiUrl}}",
    ROOT: "{{webUrl}}",
    GOOGLE_CLIENT_ID_WEB: "{{googleClientIdWeb}}",
    GOOGLE_CLIENT_ID_IOS: "{{googleClientIdIos}}",
    GOOGLE_REVERSE_CLIENT_ID_IOS: "{{googleReverseClientIdIos}}",
    GOOGLE_API_KEY: "{{googleApiKey}}",
    FACEBOOK_APP_ID: "{{facebookAppId}}",
    FACEBOOK_CLIENT_TOKEN: "{{facebookClientToken}}",
    CLEVER_ID: "{{cleverId}}",
    LOGIN_URI: "{{loginUri}}",
    SITE_NAME: "{{appName}}",
    LANGUAGE: "{{languageEnglish}}",
    LANGUAGE_NATIVE: "{{languageNative}}",
    SITE_OWNER: "{{appOwner}}",
    GOOGLE_PLAY_STORE_URL: "{{googlePlayStoreUrl}}",
    ITUNES_STORE_URL: "{{itunesStoreUrl}}",
    IOS_APP_ID_NUMBER: "{{iosAppIdNumber}}",
    APP_ID: "{{appId}}",
    production: {{production}},
};
