# Deploy targets for deploy.sh — copy to language repo scripts/deploy-vars.sh
# Templates live in core/scripts/examples/ (do not edit this file in your language repo).
#
#   npm run core init-language-repo-vars
#   # or: cp core/scripts/examples/deploy-vars.example.sh scripts/deploy-vars.sh
#
# scripts/deploy-vars.sh is version controlled in the language repo (not secret — hosts and paths only).

export PRODUCTION_SERVER_USER="your-production-user"
export PRODUCTION_DOCUMENT_ROOT="/home/your-production-user/public_html"
export PRODUCTION_DOMAIN_ROOT="/home/your-production-user"
export PRODUCTION_SSH_IDENTITY_FILE="$HOME/.ssh/your-key.pem"
export PRODUCTION_SSH_USER="centos"
export PRODUCTION_SSH_HOST="your-production-host.example.com"

export STAGING_SERVER_USER="your-staging-user"
export STAGING_DOCUMENT_ROOT="/home/your-staging-user/staging.example.com/public_html"
export STAGING_DOMAIN_ROOT="/home/your-staging-user/staging.example.com"
export STAGING_SSH_IDENTITY_FILE="$HOME/.ssh/your-key.pem"
export STAGING_SSH_USER="centos"
export STAGING_SSH_HOST="your-staging-host.example.com"
