# Local development paths — copy to language repo scripts/local-dev-vars.sh
# Templates live in core/scripts/examples/ (do not edit this file in your language repo).
#
#   npm run core init-language-repo-vars
#   # or: cp core/scripts/examples/local-dev-vars.example.sh scripts/local-dev-vars.sh
#
# scripts/local-dev-vars.sh is gitignored in the language repo.

# Apache document root — parent folder of backend/ after sync-local-backend runs.
# MAMP (macOS):     /Applications/MAMP/htdocs
# XAMPP (Windows):  C:/xampp/htdocs
# XAMPP (macOS):    /Applications/XAMPP/xamppfiles/htdocs
# XAMPP (Linux):    /opt/lampp/htdocs
export ELEARNING_WWW_PATH='/Applications/MAMP/htdocs'
